[package]
name = "mini-rando"
version = "0.1.0"
authors = ["Jonathan Louie <jonathanrlouie@gmail.com>"]

[dependencies]
amethyst = "0.9.0"
tiled = "0.7.2"
bitflags = "1.0.3"
rand = "0.5.5"
linked_hash_set = "0.1.3"