[package]
name = "mini-rando"
version = "0.1.0"
authors = ["Jonathan Louie <jonathanrlouie@gmail.com>"]

[dependencies]
amethyst = "0.10.0"
tiled = "0.7.2"
bitflags = "1.0.3"
rand = "0.5.5"
linked_hash_set = "0.1.3"
serde = "1.0"
serde_derive = "1.0"
num-traits = "0.2.6"